config/routes.rb
Autismconnect::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  mount Forem::Engine, :at => '/forums'


  resources :documents

  resources :events
  resources :links
  resources :articles

  resources :charges

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  resources :users, only: [:index, :show, :update]

  
  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit'
  post '/profile' => 'users#update'
  get '/search' => 'search#index', :as => :search
  get '/directory' => 'users#directory', :as => :directory
  get '/adminpanel' => 'users#adminpanel', :as => :adminpanel

  # SP 24/2/2homepage goes to views > pages > home.html.erb

  # SP homepage goes to views > pages > home.html.erb
  root :to => "pages#home"

  # SP whenever you go /<something> this will point you to pages > views > <something>.html.erb
  get '/:action' => 'pages#action'

  # devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_scope :user do
  #   get "sign_in", to: "devise/sessions#new"
  #   get "sign_up", to: "devise/registrations#new"
  # end

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  mount_uploader :asset, AssetUploader

  # acts-as-taggable relationship (alias for acts_as_taggable_on :tags)
  # gives access to information inside @articles.tags
  acts_as_taggable

  def to_s
  	self.name
  end
  def abstract
  	self.kind
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # SP 25/02/2014 - Remove authentication from index and detail pages. Edit/destroy/create requires login.
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError, :with => :unauthorized_error

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @documents = Document.all
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    authorize @document
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    authorize @document

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    authorize @document

    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    authorize @document
    
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    def unauthorized_error
      redirect_to articles_path, :alert => "You can't touch this document!"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :kind, :user_id, :asset, :tag_list)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :kind %><br>
    <%= f.text_field :kind, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id, :class => "form-control" %>
    Created by: <%= current_user.name%>  
  </div>
  <div class="form-group">
    <%= f.label :asset, "upload a file" %><br>
    <%= f.file_field :asset, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags - seperated by commas" %><br>
    <%= f.text_field :tag_list, :class => "form-control", :required => true %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="form-fields-sign-edit-event clearfix">

  <h1>Editing document</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @document, :class=> "btn btn-default btn-sm" %> |
  <%= link_to 'Back', documents_path, :class=> "btn btn-default btn-sm" %>
</div>

app/views/documents/index.html.erb
<div class="form-inner">
  <h1 class="center">Documents and Literature</h1>
  <table class="table-responsive">
    <table class="table table-condensed table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>View Document</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.kind %></td>
        <td><%= link_to document.name, document.asset_url %></td>
        <% if policy(document).edit? %>
          <td><%= link_to 'Edit', edit_document_path(document), :class => "btn btn-default btn-sm" %></td>
        <% end %>
        <% if policy(document).destroy? %>
          <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</table>

<br>
<% if policy(@documents).create? %>
  <%= link_to 'New Document', new_document_path, :class => "btn btn-primary btn-sm" %>
<% end %>
</div>

app/views/documents/new.html.erb
<div class="form-fields-sign-edit-event clearfix">

  <h1>New document</h1>

  <%= render 'form' %>

  <%= link_to 'Back', documents_path, :class=> "btn btn-default btn-sm" %>
</div>

app/views/documents/show.html.erb
<div class="article-show-inner">
  
  <h1>"<%= @document.name %>"</h1>

  <h2><%= @document.kind %></h2>

  <p>Uploaded by <%= @document.user.name %></p>
  <p>

    <h2>Categories</h2><br/>
    <% @document.tags.each do |tag| %>
    <%= link_to tag.name, { controller: :search, action: :index, search_term: tag.name }, :class => "btn btn-warning btn-sm"%>
    <% end %>
  </p>




  <%= link_to 'Edit', edit_document_path(@document), :class => "btn btn-default btn-sm" %>
  <%= link_to 'Back', documents_path, :class => "btn btn-default btn-sm"%>
</div>